# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='From',
            field=models.EmailField(default='shankarswamy294@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compose',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
