# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_auto_20170808_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compose',
            old_name='From',
            new_name='fromemail',
        ),
    ]
