# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_auto_20170808_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='fromemail',
            field=models.CharField(max_length=100),
        ),
    ]
