# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0004_auto_20170808_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compose',
            old_name='fromemail',
            new_name='email',
        ),
    ]
