# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0005_auto_20170809_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compose',
            name='email',
        ),
        migrations.AddField(
            model_name='compose',
            name='fromemail',
            field=models.EmailField(default='new@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
